from fastapi import APIRouter, HTTPException, status
from typing import List

from backend.api.schemas.driver import DriverCreate, DriverUpdate, DriverResponse
from backend.api.converters.driver import (
    load_drivers,
    find_driver_by_id,
    add_driver,
    update_driver,
    delete_driver,
    driver_to_json
)
from backend.models.driver import Driver

router = APIRouter()

# Get all drivers
@router.get("/drivers", response_model=List[DriverResponse])
def get_all_drivers():
    try:
        drivers = load_drivers()
        return [DriverResponse(**driver_to_json(d)) for d in drivers]
    except ValueError as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Data loading failed: {str(e)}"
        )

# Get a single driver
@router.get("/drivers/{driver_id}", response_model=DriverResponse) 
def get_driver(driver_id: int): 
    driver = find_driver_by_id(driver_id)
    if not driver:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Driver ID {driver_id} not found"
        )
    return DriverResponse(**driver_to_json(driver))

# Create a new driver
@router.post("/drivers", response_model=DriverResponse, status_code=status.HTTP_201_CREATED) 
def create_driver(driver_data: DriverCreate): 
    # Create Driver object (ID will be automatically generated by converter)
    new_driver = Driver(
        id=0,  # Temporary ID, will be overwritten by add_driver
        start_location=driver_data.start_location,
        vehicle_type=driver_data.vehicle_type,
        capacity=driver_data.capacity,
        available=driver_data.available
    )
    
    try:
        created_driver = add_driver(new_driver)
        return DriverResponse(**driver_to_json(created_driver))
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Creation failed: {str(e)}"
        )

# Update a driver
@router.put("/drivers/{driver_id}", response_model=DriverResponse)
def update_driver_endpoint(driver_id: int, driver_data: DriverUpdate):
    # Get existing driver
    existing_driver = find_driver_by_id(driver_id)
    if not existing_driver:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Driver ID {driver_id} not found"
        )
    
    # Use provided fields to update, keep original values if not provided
    updated_driver = Driver(
        id=driver_id,
        start_location=driver_data.start_location if driver_data.start_location is not None else existing_driver.start_location,
        vehicle_type=driver_data.vehicle_type if driver_data.vehicle_type is not None else existing_driver.vehicle_type,
        capacity=driver_data.capacity if driver_data.capacity is not None else existing_driver.capacity,
        available=driver_data.available if driver_data.available is not None else existing_driver.available
    )
    
    try:
        result = update_driver(driver_id, updated_driver)
        if not result:
            raise HTTPException(
                status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                detail="Update failed"
            )
        return DriverResponse(**driver_to_json(result))
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Update failed: {str(e)}"
        )


# Delete a driver
@router.delete("/drivers/{driver_id}")
def delete_driver_endpoint(driver_id: int):
    success = delete_driver(driver_id)
    if not success:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Driver ID {driver_id} not found"
        )
    return {"message": f"Driver ID {driver_id} deleted successfully"}
