from fastapi import APIRouter, HTTPException, status
from typing import List

from backend.api.schemas.task import TaskCreate, TaskUpdate, TaskResponse
from backend.api.converters.task import (
    load_tasks,
    find_task_by_id,
    add_task,
    update_task,
    save_tasks,
    delete_task,
    task_to_json
)
from backend.models.task import Task

router = APIRouter(prefix="/tasks", tags=["tasks"])

# Get all tasks
@router.get("/", response_model=List[TaskResponse])
def get_all_tasks():
    try:
        tasks = load_tasks()
        return [TaskResponse(**task_to_json(t)) for t in tasks]
    except ValueError as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Data loading failed: {str(e)}"
        )

# Get a single task
@router.get("/{task_id}", response_model=TaskResponse) 
def get_task(task_id: int): 
    task = find_task_by_id(task_id)
    if not task:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Task ID {task_id} not found"
        )
    return TaskResponse(**task_to_json(task))

# Create a new task
@router.post("/", response_model=TaskResponse, status_code=status.HTTP_201_CREATED) 
def create_task(task_data: TaskCreate): 
    # Create Task object (ID will be automatically generated by converter)
    new_task = Task(
        id=0,  # Temporary ID, will be overwritten by add_task
        pickup_location=task_data.pickup_location,
        dropoff_location=task_data.dropoff_location,
        weight=task_data.weight,
        status=task_data.status
    )
    
    try:
        created_task = add_task(new_task)
        return TaskResponse(**task_to_json(created_task))
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Creation failed: {str(e)}"
        )

# Update a task
@router.put("/{task_id}", response_model=TaskResponse)
def update_task_endpoint(task_id: int, task_data: TaskUpdate):
    # Get existing task
    existing_task = find_task_by_id(task_id)
    if not existing_task:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Task ID {task_id} not found"
        )
    
    # Use provided fields to update, keep original values if not provided
    updated_task = Task(
        id=task_id,
        pickup_location=task_data.pickup_location if task_data.pickup_location is not None else existing_task.pickup_location,
        dropoff_location=task_data.dropoff_location if task_data.dropoff_location is not None else existing_task.dropoff_location,
        weight=task_data.weight if task_data.weight is not None else existing_task.weight,
        status=task_data.status if task_data.status is not None else existing_task.status
    )
    
    try:
        result = update_task(task_id, updated_task)
        if not result:
            raise HTTPException(
                status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                detail="Update failed"
            )
        return TaskResponse(**task_to_json(result))
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Update failed: {str(e)}"
        )


# Delete a task
@router.delete("/{task_id}")
def delete_task_endpoint(task_id: int):
    success = delete_task(task_id)
    if not success:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Task ID {task_id} not found"
        )
    return {"message": f"Task ID {task_id} deleted successfully"}
